-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 22:26:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema world_cities
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema world_cities
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `world_cities` DEFAULT CHARACTER SET utf8 ;
USE `world_cities` ;

-- -----------------------------------------------------
-- Table `world_cities`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `world_cities`.`countries` ;

CREATE TABLE IF NOT EXISTS `world_cities`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `world_cities`.`regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `world_cities`.`regions` ;

CREATE TABLE IF NOT EXISTS `world_cities`.`regions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `world_cities`.`areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `world_cities`.`areas` ;

CREATE TABLE IF NOT EXISTS `world_cities`.`areas` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `world_cities`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `world_cities`.`cities` ;

CREATE TABLE IF NOT EXISTS `world_cities`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `countries_id` INT NOT NULL,
  `regions_id` INT NOT NULL,
  `areas_id` INT NOT NULL,
  `population` INT UNSIGNED NULL,
  `founded_at` DATE NULL,
  `description` BLOB NULL,
  PRIMARY KEY (`id`, `countries_id`, `regions_id`),
  INDEX `fk_cities_countries_idx` (`countries_id` ASC) VISIBLE,
  INDEX `fk_cities_regions1_idx` (`regions_id` ASC) VISIBLE,
  INDEX `fk_cities_areas1_idx` (`areas_id` ASC) VISIBLE,
  CONSTRAINT `fk_cities_countries`
    FOREIGN KEY (`countries_id`)
    REFERENCES `world_cities`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cities_regions1`
    FOREIGN KEY (`regions_id`)
    REFERENCES `world_cities`.`regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cities_areas1`
    FOREIGN KEY (`areas_id`)
    REFERENCES `world_cities`.`areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
